variables:
  S3_BUCKET_NAME: "ryanirelan.com"
deploy:
  image: mijingo/jekyll-aws:latest
  script:
  - sudo gem install nokogiri -v '1.6.6.2' -- --use-system-libraries --with-xml2-include=/usr/include/libxml2 --with-xml2-lib=/usr/lib
  - bundle config --global silence_root_warning 1
  - bundle install
  - bundle clean --force
  - jekyll build
  - aws s3 cp ./_site s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"