variables:
  S3_BUCKET_NAME: "ryanirelan.com"
deploy:
  image: mikemackintosh/gitlab-jekyll
  script:
  - jekyll build
  - aws s3 cp ./_site s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"