variables:
    S3_BUCKET_NAME: "ryanirelan.com"
      deploy:
            image: python:latest
                  script:
                        - pip install awscli
                            - aws s3 cp ./_site s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"
