variables:
  S3_BUCKET_NAME: "ryanirelan.com"
deploy:
  image: mijingo/jekyll-aws:latest
  script:
  - gem install pkg-config
  - bundle config --global silence_root_warning 1
  - bundle config build.nokogiri
  - bundle install
  - bundle clean --force
  - jekyll build
  - aws s3 cp ./_site s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"